exports.Config = {
    DEBUG: 0,
    lang: "zh-ch",
    version: "1.0.0.107",
    //http://150.109.83.195/
    // serverList: "https://gs-gtmz.meogames.com/serverlist.php",
    serverList: "https://kortest-gtmz.meogames.com/serverlist.php",      // 韩国QA
    // serverList: "https://gtkxy.xianyuyouxi.com/serverlist.php",      // 研发测试服
    // https://gtkxy-korea-test.xianyuyouxi.com/serverlist.php   //研发测试服2 韩国
    // gtk_gs_ts.meogames.com
    // serverList: "http://150.109.83.195/serverlist.php",
    // serverList: "http://150.109.83.195/serverlist.php",
    youdong_appid: "189",
    USER_LOGIN_URL: "http://129.211.8.205/fastLogin.php",
    // USER_REGISTER_URL: "http://usercenter.zhisnet.cn/register.php",
    // SEND_CODE_URL: "http://usercenter.zhisnet.cn/sms/sendCode.php",
    // BIND_PHONE_URL: "http://usercenter.zhisnet.cn/sms/bindPhonenum.php",
    // UNBIND_PHONE_URL: "http://usercenter.zhisnet.cn/sms/unbindPhonenum.php",
    // RESET_PWD_URL: "http://usercenter.zhisnet.cn/sms/resetPwd.php",
    channel_id:"1",
    url: "",
    serId: 0,
    servername: "",
    uid: 0,
    token: "",
    backurl: "",
    gamename: "",
    parm1: "",
    parm2: "",
    parm3: "",
    parm4: "",
    pf: "xianyu", //是否使用sdk登录
    login_by_sdk: !0,
    // pf: "local",
    // login_by_sdk: 0,
    pfv: "",
    pfn: "",
    skin: "gb",
    name_prefix: "",
    account: "",
    password: "",
    clickBtnSound: "dianj",
    isRSN: !1,
    // apiPath: "https://gs-gtmz.meogames.com/version.php",
    apiPath: "https://kortest-gtmz.meogames.com/version.php",
    showHeight: 1280,
    recharge_url: "",
    version_code: 0,
    target_version_code: 0,
    download_url: "https://play.google.com/store/apps/details?id=com.xhhd.xianyugame.korea",
    enter_game: !0,
    main_tuoluo_action: !1,
    isOpenUserCenter: !1,
    isNewServerList: !1,
    questUrl: "",
    freebackUrl: "",
    isHideChange: !1,
    remoteVersion: "1",
    hotUpdateUrl: "http:baidu.com",
    logo: "",
    showLang: !0,
    isShowShare: !0,
    activityUrl: "",
    share_meta_url: "",
    isShowBanhao: !1,
    pfApi: "",
    isShowMyServer: !1,
    accountprefix: "",
    isShowMonthCard: !0,
    isShowChengHao: !0,
    isHideChangeAccount: function() {
        return !!exports.Config.isHideChange || "epandquick_zjfh" == exports.Config.pf;
    },
    isSocket: !1,
    addShowCreateHeadId: [],
    changeLang: [],
    isAutoLogin: !1
};
